name: openapi_repository
description: This package generates ListBloc and DataBloc using openapi_repository_annotations.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  openapi_repository_annotations:
    git:
      url: https://github.com/adar2378/list_bloc.git
      ref: master
      path: packages/openapi_repository_annotations
  list_bloc:
    git:
      url: https://github.com/adar2378/list_bloc.git
      ref: master
      path: packages/list_bloc
  build: ^2.3.0
  built_collection: ^5.1.1
  built_value: ^8.3.2
  dio: ^4.0.6
  mustache_template: ^2.0.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.2
  freezed_annotation: ^2.0.3
  analyzer: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.16.0
