name: flutter_list_bloc
description: A Flutter package to display the data loaded with list_bloc.
version: 3.0.3
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  list_bloc: ^3.0.0
  flutter_bloc: ^8.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  list_bloc:
#    path: ../list_bloc

flutter:
