name: flutter_list_bloc
description: A Flutter package to display the data loaded with list_bloc.
version: 4.1.1
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  list_bloc: ^3.1.1
  flutter_bloc: ^8.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

#  list_bloc:
#    path: ../list_bloc

flutter:
