name: list_bloc
description: A BLoC library for loading data from an api end-point with filtering and pagination.
version: 3.1.0
homepage: https://github.com/djangoflow/list_bloc/

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  freezed_annotation: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  equatable: ^2.0.5
  bloc_test: ^9.1.0

